device: 'cuda'
## device: 'cpu'
graphrnn_baseline: False
permutation: 'random'
bias_constant: 0.25
# sequence size
min_num_node: 2
max_num_node: 50
max_edge_len: 25

# node/edge categories
num_node_categories: 151
num_edge_categories: 53
node_EOS_token: 150
edge_SOS_token: 52
no_edge_token: 51

# embedding
node_emb_size: 16
edge_emb_size: 8

# GRU_graph
ggru_emb_size: 64
ggru_hidden_size: 32
ggru_num_layers: 3

# MLP_node
mlp_input_size: 32
mlp_emb_size: 32
mlp_out_size: 151

# GRU_edge
egru_hidden_size: 16
egru_emb_input_size: 32
egru_num_layers: 3
egru_emb_output_size: 32
egru_output_size: 51
